// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {networks} from '../models';
import {config} from '../models';
import {marketplace} from '../models';
import {plugins} from '../models';
import {terminal} from '../models';

export function AcceptEULA():Promise<void>;

export function ClearTerminal():Promise<void>;

export function DetectJava():Promise<main.JavaInfo>;

export function DisablePlugin(arg1:string):Promise<void>;

export function EnablePlugin(arg1:string):Promise<void>;

export function GetClaimedServers():Promise<Array<networks.ClaimedServer>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetMarketplaceAuthURL():Promise<string>;

export function GetNetworksAuthURL():Promise<string>;

export function GetOwnedPlugins():Promise<Array<marketplace.OwnedPlugin>>;

export function GetPlugins():Promise<Array<plugins.Plugin>>;

export function GetServerState():Promise<string>;

export function GetTerminalHistory():Promise<Array<terminal.Line>>;

export function InstallNetworksCompanion():Promise<plugins.Plugin>;

export function InstallOwnedPlugin(arg1:string):Promise<plugins.Plugin>;

export function InstallPluginFromPath(arg1:string):Promise<plugins.Plugin>;

export function IsSignedIn(arg1:string):Promise<boolean>;

export function MarkVoiceGuideReady():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenPluginsFolder():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RemovePlugin(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SelectServerFolder():Promise<string>;

export function SendCommand(arg1:string):Promise<void>;

export function SetServerFolder(arg1:string):Promise<void>;

export function SignInWithToken(arg1:string,arg2:string):Promise<void>;

export function SignOut(arg1:string):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function ValidateJavaPath(arg1:string):Promise<main.JavaInfo>;

export function ValidateServerFolder(arg1:string):Promise<main.FolderValidation>;
