// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptEULA() {
  return window['go']['main']['App']['AcceptEULA']();
}

export function ClearTerminal() {
  return window['go']['main']['App']['ClearTerminal']();
}

export function DetectJava() {
  return window['go']['main']['App']['DetectJava']();
}

export function DisablePlugin(arg1) {
  return window['go']['main']['App']['DisablePlugin'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['main']['App']['EnablePlugin'](arg1);
}

export function GetClaimedServers() {
  return window['go']['main']['App']['GetClaimedServers']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMarketplaceAuthURL() {
  return window['go']['main']['App']['GetMarketplaceAuthURL']();
}

export function GetNetworksAuthURL() {
  return window['go']['main']['App']['GetNetworksAuthURL']();
}

export function GetOwnedPlugins() {
  return window['go']['main']['App']['GetOwnedPlugins']();
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetServerState() {
  return window['go']['main']['App']['GetServerState']();
}

export function GetTerminalHistory() {
  return window['go']['main']['App']['GetTerminalHistory']();
}

export function InstallNetworksCompanion() {
  return window['go']['main']['App']['InstallNetworksCompanion']();
}

export function InstallOwnedPlugin(arg1) {
  return window['go']['main']['App']['InstallOwnedPlugin'](arg1);
}

export function InstallPluginFromPath(arg1) {
  return window['go']['main']['App']['InstallPluginFromPath'](arg1);
}

export function IsSignedIn(arg1) {
  return window['go']['main']['App']['IsSignedIn'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenPluginsFolder() {
  return window['go']['main']['App']['OpenPluginsFolder']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemovePlugin(arg1) {
  return window['go']['main']['App']['RemovePlugin'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectServerFolder() {
  return window['go']['main']['App']['SelectServerFolder']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SetServerFolder(arg1) {
  return window['go']['main']['App']['SetServerFolder'](arg1);
}

export function SignInWithToken(arg1, arg2) {
  return window['go']['main']['App']['SignInWithToken'](arg1, arg2);
}

export function SignOut(arg1) {
  return window['go']['main']['App']['SignOut'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function ValidateJavaPath(arg1) {
  return window['go']['main']['App']['ValidateJavaPath'](arg1);
}

export function ValidateServerFolder(arg1) {
  return window['go']['main']['App']['ValidateServerFolder'](arg1);
}
